apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
      storage: 100Gi
  nfs:
    path: /export
    server: 1.1.1.1
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
