apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
spec:
  server:
    host: argocd.apps.hub.foo.bar
  rbac:
    defaultPolicy: 'role:readonly'
    policy: |
      g, argo-admins, role:admin
    scopes: '[groups]'
